# Generated by Django 5.2.5 on 2025-08-25 19:31

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scammer', '0002_alter_theshop_created_dislike'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='scammer.theshop'),
        ),
        migrations.RemoveField(
            model_name='like',
            name='who_liked',
        ),
        migrations.AlterField(
            model_name='theshop',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 25, 19, 30, 52, 71135, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='like',
            name='who_liked',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='users_like', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
