# Generated by Django 5.2.5 on 2025-08-27 21:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scammer', '0003_alter_like_shop_remove_like_who_liked_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theshop',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 27, 21, 35, 15, 962173, tzinfo=datetime.timezone.utc)),
        ),
    ]
