# Generated by Django 5.2.5 on 2025-08-30 21:12

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scammer', '0004_alter_theshop_created'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='who_liked',
        ),
        migrations.AlterField(
            model_name='theshop',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 30, 21, 12, 23, 225993, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='like',
            name='who_liked',
            field=models.ManyToManyField(related_name='users_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
