# Generated by Django 5.2.5 on 2025-09-03 15:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scammer', '0006_alter_theshop_created_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['-created'], 'verbose_name': 'تصویر', 'verbose_name_plural': 'تصاویر'},
        ),
        migrations.AlterModelOptions(
            name='theshop',
            options={'ordering': ['-created'], 'verbose_name': 'فروشگاه', 'verbose_name_plural': 'فروشگاه ها'},
        ),
        migrations.RemoveField(
            model_name='image',
            name='imgage_file',
        ),
        migrations.AddField(
            model_name='image',
            name='img_file',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/'),
        ),
        migrations.AlterField(
            model_name='theshop',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 3, 15, 26, 1, 724947, tzinfo=datetime.timezone.utc)),
        ),
    ]
