# Generated by Django 5.2.5 on 2025-09-11 18:42

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scammer', '0007_alter_image_options_alter_theshop_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='dislike',
            name='who_Disliked',
            field=models.ManyToManyField(blank=True, null=True, related_name='users_dislike', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='like',
            name='who_liked',
            field=models.ManyToManyField(blank=True, null=True, related_name='users_like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='theshop',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 11, 18, 42, 2, 845308, tzinfo=datetime.timezone.utc)),
        ),
    ]
