# Generated by Django 5.2.5 on 2025-09-17 18:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scammer', '0008_alter_dislike_who_disliked_alter_like_who_liked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='theshop',
            name='slug',
            field=models.SlugField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='theshop',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 17, 18, 57, 36, 747432, tzinfo=datetime.timezone.utc)),
        ),
    ]
