# Generated by Django 5.2.5 on 2025-11-06 21:26

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scammer', '0009_theshop_slug_alter_theshop_created'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='shop',
        ),
        migrations.RemoveField(
            model_name='like',
            name='who_liked',
        ),
        migrations.AddField(
            model_name='theshop',
            name='description',
            field=models.TextField(default=1, verbose_name='توضیحات'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='theshop',
            name='dislike',
            field=models.ManyToManyField(related_name='dislikes', to=settings.AUTH_USER_MODEL, verbose_name='دیس لایک ها'),
        ),
        migrations.AddField(
            model_name='theshop',
            name='like',
            field=models.ManyToManyField(related_name='likes', to=settings.AUTH_USER_MODEL, verbose_name='لایک ها'),
        ),
        migrations.AlterField(
            model_name='theshop',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 6, 21, 26, 50, 436770, tzinfo=datetime.timezone.utc)),
        ),
        migrations.DeleteModel(
            name='DisLike',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
