# Generated by Django 5.2.5 on 2025-11-06 21:33

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scammer', '0010_remove_like_shop_remove_like_who_liked_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='theshop',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 6, 21, 33, 35, 936167, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='theshop',
            name='dislike',
            field=models.ManyToManyField(blank=True, related_name='dislikes', to=settings.AUTH_USER_MODEL, verbose_name='دیس لایک ها'),
        ),
        migrations.AlterField(
            model_name='theshop',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL, verbose_name='لایک ها'),
        ),
    ]
